---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: gitops-lab
data:
  index.html: |
    Ini tampilan dari NGINX dan nama saya Malik diupdate melalui ArgoCD
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-index
  namespace: gitops-lab
data:
  index.html: |
    Ini tampilan dari HTTPD dan nama saya Malik diupdate melalui ArgoCD
