---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: gitops-lab
spec:
  type: NodePort
  selector:
    app: simple-nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: gitops-lab
spec:
  type: NodePort
  selector:
    app: simple-httpd
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
